--CONSULTA PARA PRODUTOS COM VALORES ABAIXO DE 1000R$ E QUE SEJAM DA CATEGORIA ELETRÔNICOS;  

SELECT * FROM PRODUCT  P
NATURAL JOIN PRODUCT_DETAIL PD
WHERE P.unit_price < 1000
AND PD.category = 'Eletrônicos';

--CONSULTA QUE RETORNA A CATEGORIA E A MEDIA DE PREÇOS DAS CATEGORIAS EM QUE OS PRODUTOS TEM MEDIA DE CLASSIFICAÇÃO MAIOR QUE 5.

SELECT category , avg(unit_price) 
	FROM PRODUCT
	NATURAL JOIN PRODUCT_DETAIL
    GROUP BY category
    	HAVING avg(rating) > 5;

--CONSULTA QUE RETORNA O EMAIL DA PESSOA E A QUANTIDADE DE PESSOAS QUE POSSUEM NIVEL DE SATISFAÇÃO MENOR QUE 3 AI PODEMOS ENVIAR DESCONTO NO EMAIL XDDDDDD.

SELECT count(id_person) as "Clientes Insatisfeitos" FROM CLIENT_REPORT
	NATURAL JOIN PERSON
    WHERE satisfaction_level > 3
    
    UNION 
    
SELECT email FROM CLIENT_REPORT
	NATURAL JOIN PERSON
    WHERE satisfaction_level > 3;

--CONSULTA QUE RETORNA OS PEDIDOS REALIZADOS APROVADOS , COM TIPO DE PAGAMENTO CREDITO E POR ORDER CRESCENTE DA DATA DO PEDIDO.

SELECT * FROM ORDERS
	NATURAL JOIN PRODUCT
    WHERE order_state = "Aprovado"
    AND type_of_payment = "C"
    ORDER BY order_date asc;

--FILTROS MAIS SIMPLES QUE PODERAM SER UTILIZADOS PARA ORDERNAR OS PRODUTOS


SELECT * FROM PRODUCT
	ORDER BY unit_price asc;
    

SELECT * FROM PRODUCT
	ORDER BY unit_price desc;


SELECT * FROM PRODUCT 
	ORDER BY rating asc;


SELECT * FROM PRODUCT 
	ORDER BY rating desc;


--VIEW PARA APRESENTAR O CARRINHO DO CLIENTE COM O A SOMA DO TOTAL PRICE DE TODOS OS SEUS CARRINHOS 

CREATE OR REPLACE VIEW view_shopping_cart(id_person,total_price) AS 

	SELECT id_person,sum(total_price) 
		FROM SHOPPING_CART 
        GROUP BY 1;
    

SELECT * FROM view_shopping_cart;

